name: CI/CD

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit Test
      run: |
        make test

    - name: Integration Test
      run: |
        make integration
