name: CI/CD

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Linter
      run: |
        make lint

    - name: Static Test
      run: |
        make static
        
    - name: Unit Test
      run: |
        make test
